sudo: false
language: python
python:
   - "3.8"
before_install:
   - pip install poetry
install:
   - poetry install -v
before_script:
   - export COVERAGE_PROCESS_START="${PWD}/.coveragerc"
   - cd alphabetsoup/tests/testdata
script:
   - nox -s tests
after_success:
   - coverage combine
   - cp /tmp/.coverage .
   - bash <(curl -s https://codecov.io/bash) -X gcov
